engines:
  rubocop:
    enabled: true
  golint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
languages:
  Ruby: true
  JavaScript: true
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- public/**
- public/assets_test/**
- vendor/**/*
- lib/assets/**